Add 'acronym' selectors to existing 'abbr' selectors
ikrishg/reseter.css pull request #39
Opened 2021-05-06 12:12 UTC by Zipher007

### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [X] I followed the contributing guidelines: [https://github.com/krishdevdb/reseter.css/blob/master/contributing.md](https://github.com/krishdevdb/reseter.css/blob/master/contributing.md)

### Which change are you proposing?

- [X] Adding A New Element's Reset
- [X] Editing A Old Element's Reset
- [ ] Removing A Elements's Reset

> Write Something About It Here

Changed the `abbr` selector to select both `abbr`, `acronym`

My PR Meets The Following Criterias:

- [ ] It Redifines Usefull Defaults (If you are doing it for h1 you redifine the font size to be big enough)
- [ ] My Content Is Responsive If Applicable (If you are defining any `px` values please convert them to `rem` for responsiveness)
- [X] My Content Is Tested. That It Doesn't Breaks The Element
- [X] My Content Is Not My Personal Opinion
- [ ] I have used the command `yarn *:build`

I've added the following sources:

- [X] less
- [X] scss
- [ ] sass
- [ ] stylus

> Please replace this line with an explanation of why you think these changes should be made.

In order to support the tags like `acronym`

2021-05-06 12:33 UTC, krishdevdb commented
@Zipher007 Thanks for contributing I've added a pr to your fork regarding the sass src. Could you merge it. So that we can merge this pr

2021-05-07 01:20 UTC, krishdevdb requested changes
Please merge https://github.com/Zipher007/reseter.css/pull/1

So that we can merge this pr

2021-05-07 10:04 UTC, Zipher007 commented
Yeah! done that ! So sorry for the late response !!😕

2021-05-07 10:04 UTC, krishdevdb approved these changes
LGMT Thanks for contributing.

@all-contributors add @Zipher007 for code

2021-05-07 10:05 UTC, merged